### PR TITLE
18 exit codes

### LINKED ISSUE #18: Exit code for CI
Hello, 

It could be very useful to add an option like `--set-exit-on-alarm` and `--set-exit-on-warning` to allow this library to make a pipeline fail.

I'm talking about GitLab here, but I think that exit code are used in other CI tools to made them fail.

### PR DESCRIPTION
**Pull request by Anrock**
Closes #18

### CODE REVIEW

File: lib/src/models/violation_level.dart [hunk 1]
```diff
@@ -21,4 +21,15 @@ class ViolationLevel {
...
+  @override
+  int compareTo(ViolationLevel other) {
+    final valuesList = values.toList(growable: false);
+    return valuesList.indexOf(this).compareTo(valuesList.indexOf(other));
+  }
+
+  bool operator >(ViolationLevel other) => compareTo(other) > 0;
+  bool operator >=(ViolationLevel other) => compareTo(other) >= 0;
+  bool operator <(ViolationLevel other) => compareTo(other) < 0;
+  bool operator <=(ViolationLevel other) => compareTo(other) <= 0;
```
Comment (dkrutskikh) [inline lib/src/models/violation_level.dart:34]: @Anrock after this change, we need to be refactor UtilitySelector. functionViolationLevel

File: lib/src/reporters/utility_selector.dart [hunk 2]
```diff
@@ -139,6 +139,22 @@ class UtilitySelector {
   static bool isIssueLevel(ViolationLevel level) =>
       level == ViolationLevel.warning || level == ViolationLevel.alarm;
 
+  static ViolationLevel maxViolationLevel(
+          Iterable<ComponentRecord> records, Config config) =>
+      records
+          .expand((componentRecord) => componentRecord.records.values.map(
+              (functionRecord) =>
+                  UtilitySelector.functionReport(functionRecord, config)))
+          .fold(
```
Comment (dkrutskikh) [inline lib/src/reporters/utility_selector.dart:148]: @Anrock why you use fold instead quiver.max ?
